// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: market_plant/market_plant.proto

#include "market_plant/market_plant.pb.h"
#include "market_plant/market_plant.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace market_plant {
namespace v1 {

static const char* MarketPlantService_method_names[] = {
  "/market_plant.v1.MarketPlantService/StreamUpdates",
  "/market_plant.v1.MarketPlantService/UpdateSubscriptions",
};

std::unique_ptr< MarketPlantService::Stub> MarketPlantService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MarketPlantService::Stub> stub(new MarketPlantService::Stub(channel, options));
  return stub;
}

MarketPlantService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamUpdates_(MarketPlantService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_UpdateSubscriptions_(MarketPlantService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::market_plant::v1::StreamResponse>* MarketPlantService::Stub::StreamUpdatesRaw(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request) {
  return ::grpc::internal::ClientReaderFactory< ::market_plant::v1::StreamResponse>::Create(channel_.get(), rpcmethod_StreamUpdates_, context, request);
}

void MarketPlantService::Stub::async::StreamUpdates(::grpc::ClientContext* context, const ::market_plant::v1::Subscription* request, ::grpc::ClientReadReactor< ::market_plant::v1::StreamResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::market_plant::v1::StreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamUpdates_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::market_plant::v1::StreamResponse>* MarketPlantService::Stub::AsyncStreamUpdatesRaw(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::market_plant::v1::StreamResponse>::Create(channel_.get(), cq, rpcmethod_StreamUpdates_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::market_plant::v1::StreamResponse>* MarketPlantService::Stub::PrepareAsyncStreamUpdatesRaw(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::market_plant::v1::StreamResponse>::Create(channel_.get(), cq, rpcmethod_StreamUpdates_, context, request, false, nullptr);
}

::grpc::Status MarketPlantService::Stub::UpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::market_plant::v1::UpdateSubscriptionRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateSubscriptions_, context, request, response);
}

void MarketPlantService::Stub::async::UpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::market_plant::v1::UpdateSubscriptionRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateSubscriptions_, context, request, response, std::move(f));
}

void MarketPlantService::Stub::async::UpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateSubscriptions_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* MarketPlantService::Stub::PrepareAsyncUpdateSubscriptionsRaw(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::market_plant::v1::UpdateSubscriptionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateSubscriptions_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* MarketPlantService::Stub::AsyncUpdateSubscriptionsRaw(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateSubscriptionsRaw(context, request, cq);
  result->StartCall();
  return result;
}

MarketPlantService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MarketPlantService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< MarketPlantService::Service, ::market_plant::v1::Subscription, ::market_plant::v1::StreamResponse>(
          [](MarketPlantService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::market_plant::v1::Subscription* req,
             ::grpc::ServerWriter<::market_plant::v1::StreamResponse>* writer) {
               return service->StreamUpdates(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MarketPlantService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MarketPlantService::Service, ::market_plant::v1::UpdateSubscriptionRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MarketPlantService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::market_plant::v1::UpdateSubscriptionRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->UpdateSubscriptions(ctx, req, resp);
             }, this)));
}

MarketPlantService::Service::~Service() {
}

::grpc::Status MarketPlantService::Service::StreamUpdates(::grpc::ServerContext* context, const ::market_plant::v1::Subscription* request, ::grpc::ServerWriter< ::market_plant::v1::StreamResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status MarketPlantService::Service::UpdateSubscriptions(::grpc::ServerContext* context, const ::market_plant::v1::UpdateSubscriptionRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace market_plant
}  // namespace v1
#include <grpcpp/ports_undef.inc>

