// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: market_plant/market_plant.proto
#ifndef GRPC_market_5fplant_2fmarket_5fplant_2eproto__INCLUDED
#define GRPC_market_5fplant_2fmarket_5fplant_2eproto__INCLUDED

#include "market_plant/market_plant.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace market_plant {
namespace v1 {

class MarketPlantService final {
 public:
  static constexpr char const* service_full_name() {
    return "market_plant.v1.MarketPlantService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Server-side streaming
    std::unique_ptr< ::grpc::ClientReaderInterface< ::market_plant::v1::StreamResponse>> StreamUpdates(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::market_plant::v1::StreamResponse>>(StreamUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::market_plant::v1::StreamResponse>> AsyncStreamUpdates(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::market_plant::v1::StreamResponse>>(AsyncStreamUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::market_plant::v1::StreamResponse>> PrepareAsyncStreamUpdates(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::market_plant::v1::StreamResponse>>(PrepareAsyncStreamUpdatesRaw(context, request, cq));
    }
    // Control-plane for modifying subscriptions
    virtual ::grpc::Status UpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::google::protobuf::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> AsyncUpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(AsyncUpdateSubscriptionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>> PrepareAsyncUpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>>(PrepareAsyncUpdateSubscriptionsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Server-side streaming
      virtual void StreamUpdates(::grpc::ClientContext* context, const ::market_plant::v1::Subscription* request, ::grpc::ClientReadReactor< ::market_plant::v1::StreamResponse>* reactor) = 0;
      // Control-plane for modifying subscriptions
      virtual void UpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::market_plant::v1::StreamResponse>* StreamUpdatesRaw(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::market_plant::v1::StreamResponse>* AsyncStreamUpdatesRaw(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::market_plant::v1::StreamResponse>* PrepareAsyncStreamUpdatesRaw(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* AsyncUpdateSubscriptionsRaw(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::Empty>* PrepareAsyncUpdateSubscriptionsRaw(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::market_plant::v1::StreamResponse>> StreamUpdates(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::market_plant::v1::StreamResponse>>(StreamUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::market_plant::v1::StreamResponse>> AsyncStreamUpdates(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::market_plant::v1::StreamResponse>>(AsyncStreamUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::market_plant::v1::StreamResponse>> PrepareAsyncStreamUpdates(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::market_plant::v1::StreamResponse>>(PrepareAsyncStreamUpdatesRaw(context, request, cq));
    }
    ::grpc::Status UpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::google::protobuf::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> AsyncUpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(AsyncUpdateSubscriptionsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>> PrepareAsyncUpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>>(PrepareAsyncUpdateSubscriptionsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamUpdates(::grpc::ClientContext* context, const ::market_plant::v1::Subscription* request, ::grpc::ClientReadReactor< ::market_plant::v1::StreamResponse>* reactor) override;
      void UpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)>) override;
      void UpdateSubscriptions(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::market_plant::v1::StreamResponse>* StreamUpdatesRaw(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request) override;
    ::grpc::ClientAsyncReader< ::market_plant::v1::StreamResponse>* AsyncStreamUpdatesRaw(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::market_plant::v1::StreamResponse>* PrepareAsyncStreamUpdatesRaw(::grpc::ClientContext* context, const ::market_plant::v1::Subscription& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* AsyncUpdateSubscriptionsRaw(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* PrepareAsyncUpdateSubscriptionsRaw(::grpc::ClientContext* context, const ::market_plant::v1::UpdateSubscriptionRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamUpdates_;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateSubscriptions_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Server-side streaming
    virtual ::grpc::Status StreamUpdates(::grpc::ServerContext* context, const ::market_plant::v1::Subscription* request, ::grpc::ServerWriter< ::market_plant::v1::StreamResponse>* writer);
    // Control-plane for modifying subscriptions
    virtual ::grpc::Status UpdateSubscriptions(::grpc::ServerContext* context, const ::market_plant::v1::UpdateSubscriptionRequest* request, ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamUpdates() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamUpdates(::grpc::ServerContext* /*context*/, const ::market_plant::v1::Subscription* /*request*/, ::grpc::ServerWriter< ::market_plant::v1::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamUpdates(::grpc::ServerContext* context, ::market_plant::v1::Subscription* request, ::grpc::ServerAsyncWriter< ::market_plant::v1::StreamResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateSubscriptions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateSubscriptions() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_UpdateSubscriptions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSubscriptions(::grpc::ServerContext* /*context*/, const ::market_plant::v1::UpdateSubscriptionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateSubscriptions(::grpc::ServerContext* context, ::market_plant::v1::UpdateSubscriptionRequest* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamUpdates<WithAsyncMethod_UpdateSubscriptions<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamUpdates() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::market_plant::v1::Subscription, ::market_plant::v1::StreamResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::market_plant::v1::Subscription* request) { return this->StreamUpdates(context, request); }));
    }
    ~WithCallbackMethod_StreamUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamUpdates(::grpc::ServerContext* /*context*/, const ::market_plant::v1::Subscription* /*request*/, ::grpc::ServerWriter< ::market_plant::v1::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::market_plant::v1::StreamResponse>* StreamUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::market_plant::v1::Subscription* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_UpdateSubscriptions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateSubscriptions() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::market_plant::v1::UpdateSubscriptionRequest, ::google::protobuf::Empty>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::market_plant::v1::UpdateSubscriptionRequest* request, ::google::protobuf::Empty* response) { return this->UpdateSubscriptions(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateSubscriptions(
        ::grpc::MessageAllocator< ::market_plant::v1::UpdateSubscriptionRequest, ::google::protobuf::Empty>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::market_plant::v1::UpdateSubscriptionRequest, ::google::protobuf::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateSubscriptions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSubscriptions(::grpc::ServerContext* /*context*/, const ::market_plant::v1::UpdateSubscriptionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateSubscriptions(
      ::grpc::CallbackServerContext* /*context*/, const ::market_plant::v1::UpdateSubscriptionRequest* /*request*/, ::google::protobuf::Empty* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamUpdates<WithCallbackMethod_UpdateSubscriptions<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamUpdates() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamUpdates(::grpc::ServerContext* /*context*/, const ::market_plant::v1::Subscription* /*request*/, ::grpc::ServerWriter< ::market_plant::v1::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_UpdateSubscriptions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateSubscriptions() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_UpdateSubscriptions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSubscriptions(::grpc::ServerContext* /*context*/, const ::market_plant::v1::UpdateSubscriptionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamUpdates() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamUpdates(::grpc::ServerContext* /*context*/, const ::market_plant::v1::Subscription* /*request*/, ::grpc::ServerWriter< ::market_plant::v1::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamUpdates(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateSubscriptions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateSubscriptions() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_UpdateSubscriptions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSubscriptions(::grpc::ServerContext* /*context*/, const ::market_plant::v1::UpdateSubscriptionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateSubscriptions(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamUpdates() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamUpdates(context, request); }));
    }
    ~WithRawCallbackMethod_StreamUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamUpdates(::grpc::ServerContext* /*context*/, const ::market_plant::v1::Subscription* /*request*/, ::grpc::ServerWriter< ::market_plant::v1::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateSubscriptions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateSubscriptions() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateSubscriptions(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateSubscriptions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateSubscriptions(::grpc::ServerContext* /*context*/, const ::market_plant::v1::UpdateSubscriptionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateSubscriptions(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateSubscriptions : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateSubscriptions() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::market_plant::v1::UpdateSubscriptionRequest, ::google::protobuf::Empty>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::market_plant::v1::UpdateSubscriptionRequest, ::google::protobuf::Empty>* streamer) {
                       return this->StreamedUpdateSubscriptions(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateSubscriptions() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateSubscriptions(::grpc::ServerContext* /*context*/, const ::market_plant::v1::UpdateSubscriptionRequest* /*request*/, ::google::protobuf::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateSubscriptions(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::market_plant::v1::UpdateSubscriptionRequest,::google::protobuf::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UpdateSubscriptions<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamUpdates() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::market_plant::v1::Subscription, ::market_plant::v1::StreamResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::market_plant::v1::Subscription, ::market_plant::v1::StreamResponse>* streamer) {
                       return this->StreamedStreamUpdates(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamUpdates(::grpc::ServerContext* /*context*/, const ::market_plant::v1::Subscription* /*request*/, ::grpc::ServerWriter< ::market_plant::v1::StreamResponse>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamUpdates(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::market_plant::v1::Subscription,::market_plant::v1::StreamResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamUpdates<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamUpdates<WithStreamedUnaryMethod_UpdateSubscriptions<Service > > StreamedService;
};

}  // namespace v1
}  // namespace market_plant


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_market_5fplant_2fmarket_5fplant_2eproto__INCLUDED
